version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      postgres:
       condition: service_healthy

  postgres:
    image: postgres:13.3
    env_file:
      "./database.env"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 2s
      retries: 2
      timeout: 5s
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      "./.env"
    ports:
      - 15672:15672
      - 5672:5672
