[tool.poetry]
name = "test_python_semple_service"
version = "0.1.0"
description = ""
authors = ["dimanah10 <dimanah10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^1.0.4"
markupsafe = "2.0.1"
requests = "2.28.1"
hypothesis = "6.68.2"
